accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.list, name="list"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_update, name='profile_update'),
    path('<int:user_pk>/', views.detail, name="detail"),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('search/', views.search, name='search'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name="list"),
    path('new/', views.create, name="create"),
    path('<int:posts_pk>/', views.detail, name="detail"),
    path('<int:posts_pk>/edit/', views.edit, name="edit"),
    path('<int:posts_pk>/delete/', views.delete, name="delete"),
    path('<int:posts_pk>/like/', views.like, name="like"),
    path('<int:posts_pk>/comments/new/', views.comment_new, name="comment_new"),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(
                    settings.AUTH_USER_MODEL, 
                    related_name='followings'
                    )

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=30)
    introduction = models.TextField()
    image = ProcessedImageField(
                    processors=[ResizeToFill(300, 300)],
                    format='JPEG',
                    options={'quality': 150},
        )

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import Profile

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super(UserCustomCreationForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label=''
            field.help_text=''
        self.fields['email'].widget.attrs.update({'placeholder': '이메일 주소', 'class': 'input-box'})
        self.fields['username'].widget.attrs.update({'placeholder': '사용자 이름', 'class': 'input-box'})
        self.fields['password1'].widget.attrs.update({'placeholder': '비밀번호', 'class': 'input-box'})
        self.fields['password2'].widget.attrs.update({'placeholder': '비밀번호 확인', 'class': 'input-box'})
    
        
        # self.fields['password1'].label = ''
        # self.fields['password1'].help_text = ''
        # self.fields['username'].widget.attrs.update({'placeholder': ''})
        
class AuthenticationForm(AuthenticationForm):
    class Meta:
        fields = ('username', 'password',)
        
    def __init__(self, *args, **kwargs):
        super(AuthenticationForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label=''
        self.fields['username'].widget.attrs.update({'placeholder': '사용자 이름', 'class': 'input-box'})
        self.fields['password'].widget.attrs.update({'placeholder': '비밀번호', 'class': 'input-box'})
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user', )
        
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.label=''
        self.fields['nickname'].widget.attrs.update({'placeholder': '사용자 이름', 'class': 'input-box'})
        self.fields['introduction'].widget.attrs.update({'placeholder': '소개', 'class': 'input-box'})
        self.fields['image'].widget.attrs.update({'class': 'input-box',})    
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
# from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.conf import settings

from .forms import UserCustomCreationForm, AuthenticationForm, ProfileForm
from .models import Profile

# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
    if request.method == "POST":
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            Profile.objects.create(user=user)
            user_login(request, user)
            return redirect('accounts:profile_update')
    else:    
        user_form = UserCustomCreationForm()
    context = {'user_form': user_form}
    return render(request, 'accounts/forms.html', context)
    
    
def login(request):
    if request.method == "POST":
        signin_form = AuthenticationForm(request, request.POST)
        if signin_form.is_valid():
            user_login(request, signin_form.get_user())
            return redirect('posts:list')
    signin_form = AuthenticationForm()
    context = {'user_form': signin_form}
    return render(request, 'accounts/forms.html', context)
    
@login_required
def logout(request):
    user_logout(request)
    return redirect('posts:list')

@login_required
def list(request):
    # users = User.objects.all()
    User = get_user_model()
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'accounts/list.html', context)

@login_required
def profile_update(request):
    if request.method == 'POST':
        # data=request.FIELS 로 해도 됌 키워드로
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('accounts:profile')
    profile_form = ProfileForm(instance=request.user.profile)
    context = {'profile_form': profile_form}
    return render(request, 'accounts/profile_update.html', context)
    
@login_required
def profile(request):
    return render(request, 'accounts/profile.html')
    
def detail(request, user_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=user_pk)
    context = {'user_info': user}
    return render(request, 'accounts/detail.html', context)
    
@login_required
def follow(request, user_pk):
    User = get_user_model()
    target_user = get_object_or_404(User, pk=user_pk)
    if request.user in target_user.followers.all():
        target_user.followers.remove(request.user)
    else:
        target_user.followers.add(request.user)
    # print(request.resolver_match.url_name)
    return redirect('accounts:detail', user_pk)

@login_required
def search(request):
    # 1. 내가 만들어놓은 모델 -> DB
    # 2. variable routing (X)
    # 3. form (O)
    username = request.GET.get('username')
    User = get_user_model()
    user = User.objects.filter(username=username).first()
    if not user:
        print('3241')
        messages.warning(request, f'{username}을 찾을 수 없습니다.')
        return redirect('posts:list')
    return redirect('accounts:detail', user.pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
    <p>{{ user_info.username }}</p>
    <p>팔로잉 : {{ user_info.followings.all.count }}</p>
    <p>팔로워 : {{ user_info.followers.all.count }}</p>
    {% if user != user_info %}
        {% if user in user_info.followers.all %}
            <a href="{% url 'accounts:follow' user_info.pk %}">언팔</a>
        {% else %}
            <a href="{% url 'accounts:follow' user_info.pk %}">팔로우</a>
        {% endif %}
    {% endif %}
{% endblock %}

accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="form-container">
    {% if request.resolver_match.url_name == 'login' %}
    <div class="form-iphone">
        <img src="{% static 'instagram/iphone.png' %}" style="disply:inline-block;">
    </div>
    {% endif %}
    <div class="form-inner">
        <form method="POST" class="form-box">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Instagram_logo.svg/1200px-Instagram_logo.svg.png" class="logo">
            <div class="form-box-container">
                {% if request.resolver_match.url_name == 'signup' %}
                <a href="{% url 'accounts:login' %}">
                    <div class="button">
                        이미 있는 아이디로 로그인
                    </div>
                </a>
                <div class="form-or">
                    <div class="form-line"></div>
                    <div class="form-or-text">또는</div>
                    <div class="form-line"></div>
                </div>
                {% else %}
                <div style="height:15px;"></div>
                {% endif %}
                {% csrf_token %}
                {{ user_form }}
                <div class="form-submit">
                    {% if request.resolver_match.url_name == 'signup' %}
                    <input type="submit" value="가입" class="button">
                    {% else %}
                    <input type="submit" value="로그인" class="button">
                    {% endif %}
                </div>
                {% if request.resolver_match.url_name == 'signup' %}
                <div class="form-explain">
                    가입하면 Instagramu의 <b>약관</b>, <b>데이터 정책</b> 및 <b>쿠키 정책</b>에 동의하게 됩니다.
                </div>
                {% else %}
                <div class="form-explain">
                    비밀번호를 잊으셨나요?
                </div>
                {% endif %}
            </div>
        </form>
        {% if request.resolver_match.url_name == 'login' %}
        <div class="form-box">
            <div class="form-explain form-explain-bottom">
                계정이 없으신가요? <a href="{% url 'accounts:signup' %}" class="form-signuptext">가입하기</a>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/list.html
{% extends 'base.html' %}
{% block body %}
<div style="flex-direction: column;">
{% for user in users %}
{% if not user.is_superuser %}
    <div>
        <p><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></p>
    </div>
    <br>
{% endif %}
{% endfor %}
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="profile-box">
    <header class="pf-header-box">
        <div class="pf-header-img-box">
            {% if user.profile.image %}
            <img src="{{ user.profile.image.url }}" class="pf-header-img">
            {% else %}
            <img src="{% static 'instagram/undefined_profile.jpg' %}" class="pf-header-img">
            {% endif %}
        </div>
        <section class="pf-header-info-box">
            <div class="pf-header-info-nkname-box">
                <h1 class="pf-header-info-nkname">
                {% if user.profile.nickname %}
                    {{ user.profile.nickname }}
                {% else %}
                    {{ user.username }}
                {% endif %}
                </h1>
                <a class="pf-header-info-edit">
                    프로필 편집
                </a>
                <div class="pf-header-info-setting">
                    <a href="{% url 'accounts:logout' %}"><span class="nav-icon setting"></span></a>
                </div>
            </div>
            <ul class="pf-header-info-nav-box">
                <li class="pf-header-info-li-box">
                    게시물
                    <span class="fw-600">{{ user.post_set.count }}</span>
                </li>
                <li class="pf-header-info-li-box">
                    팔로워
                    <span class="fw-600">{{ user.followers.count }}</span>
                </li>
                <li class="pf-header-info-li-box">
                    팔로우
                    <span class="fw-600">{{ user.followings.count }}</span>
                </li>
            </ul>
            <div class="pf-header-info-discription-box">
                <h1 class="pf-header-info-discription">
                    {{ user.username }}
                </h1>
                <span>
                    {{ user.profile.introduction }}
                </span>
            </div>
        </section>
    </header>
    <div class="pf-nav">
        <a href="#" class="pf-nav-items">
            <span class="pf-nav-items-box">
                <div class="pf-nav-icon posts"></div>
                <span class="pf-nav-post-char">게시물</span>
            </span>
        </a>
        <a href="#" class="pf-nav-items">
            <span class="pf-nav-items-box">
                <div class="pf-nav-icon igtv"></div>
                <span class="pf-nav-post-char">IGTV</span>
            </span>
        </a>
        <a href="#" class="pf-nav-items">
            <span class="pf-nav-items-box">
                <div class="pf-nav-icon saved"></div>
                <span class="pf-nav-post-char">저장됨</span>
            </span>
        </a>
        <a href="#" class="pf-nav-items" style="margin-right: 0;">
            <span class="pf-nav-items-box">
                <div class="pf-nav-icon taged"></div>
                <span class="pf-nav-post-char">태그됨</span>
            </span>
        </a>
    </div>
    <div class="notyet">
        <br>
        공사중 입니다
    </div>
    
    
    
    
</div>
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% block body %}
<div class="form-container">
    <div class="form-inner">
        <form method="POST" class="form-box" enctype="multipart/form-data">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Instagram_logo.svg/1200px-Instagram_logo.svg.png" class="logo">
            <div class="form-box-container">
                <div style="height:15px;"></div>
                {% csrf_token %}
                {{ profile_form }}
                <div class="form-submit">
                    <input type="submit" value="수정하기" class="button">
                </div>
                <div class="form-explain">
                    음음음
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}