accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.list, name="list"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_update, name='profile_update'),
    path('<int:user_pk>/', views.detail, name="detail"),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('search/', views.search, name='search'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name="list"),
    path('new/', views.create, name="create"),
    path('<int:posts_pk>/', views.detail, name="detail"),
    path('<int:posts_pk>/edit/', views.edit, name="edit"),
    path('<int:posts_pk>/delete/', views.delete, name="delete"),
    path('<int:posts_pk>/like/', views.like, name="like"),
    path('<int:posts_pk>/comments/new/', views.comment_new, name="comment_new"),
]

instagram/templates/_footer.html
<footer class="footer-box">
    <div class="footer-inner row">
        <nav class="footer-navbox col-sm-8">
            <ul class="footer-ul">
                <li class="footer-li">INSTAGRAMU 정보</li>
                <li class="footer-li">후원</li>
                <a href="{% url 'accounts:list' %}"><li class="footer-li">회원목록</li></a>
                <li class="footer-li">어디로든 문</li>
                <li class="footer-li">???</li>
            </ul>
        </nav>
        <span class="col-sm-4">© 2019 INSTAGRAMU</span>
    </div>
</footer>

instagram/templates/_messages.html
{% if messages %}
    {% for message in messages %}
    <div{% if message.tags %} class="alert alert-{{ message.tags }}" role="alert"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

instagram/templates/_navbar.html
{% load static %}
{% if user.is_authenticated %}
<nav class="nav-box">
<div class="nav-box-fixed">
    <div class="nav-inbox">
        <div class="nav-logobox">
            <a class="nav-logo" href="/posts/">
                <div class="nav-logoinbox">
                    <span class="nav-icon instalogo"></span>
                    <div class="nav-logobar"></div>
                    <span class="nav-icon instawrite" style="height:29px; width:103px; margin-top: 7px;"></span>
                </div>
            </a>    
        </div>
        <!---->
        <form action="{% url 'accounts:search' %}" class="nav-searchbox d-none d-sm-block">
            <input name="username" class="nav-searchinput" type="search" placeholder="검색" aria-label="Search">
            <button type="submit" hidden></button>
        </form>     
        
        <div>
           
        </div>
        <!---->
        <div class="nav-nav">
            <div class="nav-navbox">
                {% if user.is_authenticated %}
                <div class="nav-iconbox">
                    <a href="{% url 'posts:create' %}" class="nav-iconlink">
                        <span class="nav-icon safari"></span>
                    </a>
                </div>
                <div class="nav-iconbox">
                    <a href="{% url 'accounts:profile' %}" class="nav-iconlink">
                        <span class="nav-icon heart"></span>
                    </a>
                </div>
                <div class="nav-iconbox">
                    <a href="{% url 'accounts:profile' %}" class="nav-iconlink">
                        <span class="nav-icon profile"></span>
                    </a>
                </div>
                {% else %}
                    <a href="{% url 'accounts:signup' %}">회원 가입</a>
                    <a href="{% url 'accounts:login' %}">로그인</a>
                {% endif %}
                
            </div>
        </div>
    </div>
</div>
</nav>
{% endif %}

instagram/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR|Noto+Serif+KR|Poor+Story" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'instagram/posts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'instagram/nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'instagram/footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'instagram/forms.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'instagram/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'instagram/main.css' %}">
    <!--<link rel="shortcut icon" href="{% static 'instagram/icons/favi.icon' %}">-->
    <!--<link rel="shortcut icon" href="favicon.ico">-->
    <!--<link rel="icon" href="{% static 'instagram/icons/favi.icon' %}">-->
    <link rel="icon" href="{% static 'instagram/icons/favi192.png' %}">
    <title>Instagramu</title>
</head>
<body>
    {% load static %}
    <div class="body-box">
        {% include '_navbar.html' %}
        {% include '_messages.html' %}
        <main class="main-box">
            {% block body %}
            {% endblock %}    
        </main>
        {% if request.resolver_match.url_name != 'list' %}
            {% include '_footer.html' %}
        {% endif %}
    </div>
    <script>
        var prevScrollpos = window.pageYOffset;
        window.onscroll = function() {
        var currentScrollPos = window.pageYOffset;
          if (prevScrollpos > currentScrollPos) {
            document.getElementById("js-up").style.top = "137px";
          } else {
            document.getElementById("js-up").style.top = "100px";
          }
          prevScrollpos = currentScrollPos;
        }
    </script>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>