accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('list/', views.list, name="list"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_update, name='profile_update'),
    path('<int:user_pk>/', views.detail, name="detail"),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('search/', views.search, name='search'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name="list"),
    path('new/', views.create, name="create"),
    path('<int:posts_pk>/', views.detail, name="detail"),
    path('<int:posts_pk>/edit/', views.edit, name="edit"),
    path('<int:posts_pk>/delete/', views.delete, name="delete"),
    path('<int:posts_pk>/like/', views.like, name="like"),
    path('<int:posts_pk>/comments/new/', views.comment_new, name="comment_new"),
]

posts/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

def post_image_path(post, filename):
    return f'posts/{post.pk}/images/{filename}'
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # user.post_set.all() - 게시글인지? 좋아요한 글인지? 알수없다
    # users = models.ManyToManyField(settings.AUTH_USER_MODEL)
    # 따라서 related_name을 추가해 헷갈리지 않게 해준다.
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')
    # image = models.ImageField()
    
    @property
    def like_count(self):
        return self.like_users.count()
    
    def __str__(self):
        return f'Post : {self.pk}'
    
    def get_absolute_url(self):
        return reverse('posts:detail', args=[self.pk])
        
class Image(models.Model):
    file = models.ImageField(upload_to=post_image_path)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    thumbnail_fill = ProcessedImageField(
            upload_to=post_image_path,
            processors = [ResizeToFill(616, 616)],
            format = 'JPEG',
            options={'quality': 150},
        )
        
class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

posts/forms.py
from .models import Post, Image
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('content',)
        widgets = {
                    'content': forms.Textarea(attrs={'placeholder': '내용을 입력하세요', 'class': 'post-textarea'})
                    }
        labels = {
                    'content': ''
                    }

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('file',)
        widgets = {
            'file': forms.FileInput(attrs={'multiple':True, 'class': 'post-input-box'}),
                    }
        labels = {
                    'file': ''
                    }

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Image, Comment
from .forms import PostForm, ImageForm
from django.forms import widgets, ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q

# Create your views here.
@login_required
def list(request):
    # from django.db.models import Q
    posts = Post.objects.filter(
                        Q(user__in=request.user.followings.values('id'))
                        | Q(user=request.user.id)
                        ).order_by('-pk')
    User = get_user_model()
    users = User.objects.all()
    context = {'posts': posts, 'users': users}
    return render(request, 'posts/list.html', context)
# @login_required
# def list(request):
#     if request.user.is_authenticated:
#         posts = Post.objects.order_by('-pk')
#         context = {'posts': posts}
#         return render(request, 'posts/list.html', context)
#     else:
#         return redirect('accounts:login')

@login_required
def create(request):
    if request.method == "POST":
        post_form = PostForm(request.POST)
        # 할 필요 없음
        # image_form = ImageForm(request.POST, request.FILES)
        if post_form.is_valid():
            
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            # 만약 여러개의 파일을 받고 싶다면 FILES안의 getlist로 받을 수 있다.
            files = request.FILES.getlist('file')
            for file in files:
                request.FILES['file'] = file
                # 위치 인자로 넘겨주려고 했던건데
                # image_form = ImageForm(request.POST, request.FILES)
                # 파일인자로 넘겨줘도 된다.
                image_form = ImageForm(files=request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post
                    image.thumbnail_fill = request.FILES.get('file')
                    print(image.thumbnail_fill)
                    print(image.thumbnail_fill.url)
                    image.save()
                    print(image.thumbnail_fill)
                    print(image.thumbnail_fill.url)
            # return redirect('posts:detail', post.pk)
            # 더 나은방법
            # return redirect(post)
            return redirect('posts:list')
    else:
        post_form = PostForm()
        image_form = ImageForm()
    context = {'post_form': post_form, 'image_form': image_form}
    return render(request, 'posts/form.html', context)

@login_required
def detail(request, posts_pk):
    post = get_object_or_404(Post, pk=posts_pk)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)

@login_required    
def edit(request, posts_pk):
    post = get_object_or_404(Post, pk=posts_pk)
    if request.method == "POST":
        post_form = PostForm(request.POST, instance=post)
        post_form.save()
        return redirect('posts:list')
    else:
        post_form = PostForm(instance=post)
    context = {'post_form': post_form}
    return render(request, 'posts/form.html', context)

@login_required
def delete(request, posts_pk):
    post = get_object_or_404(Post, pk=posts_pk)
    post.delete()
    return redirect('posts:list')

@login_required
def like(request, posts_pk):
    post = get_object_or_404(Post, pk=posts_pk)
    user = request.user
    # user가 지금 해당 게시글에 좋아요를 한 적이 있는지?
    # if user in post.like_users.all():
    #     post.like_users.remove(user)
    # else:
    #     post.like_users.add(user)
    if post.like_users.filter(pk=user.id).exists():
        post.like_users.remove(user)
    else:
        post.like_users.add(user)
    return redirect('posts:list')
    
@login_required
def comment_new(request, posts_pk):
    post = get_object_or_404(Post, pk=posts_pk)
    comment = Comment()
    comment.content = request.POST.get('content')
    comment.post = post
    comment.user = request.user
    comment.save()
    return redirect('posts:list')

posts/templates/posts/_aside.html
{% load static %}
<div class="sec-aside-box">
    <div class="sec-aside-fixed-box" id="js-up">
        <div class="sec-aside-pf-box">
            <div class="sec-aside-pf-inbox">
                <div class="sec-aside-pf-photo-box" role="button">
                    <a href="{% url 'accounts:profile' %}" class="sec-aside-pf-photo">
                        {% if user.profile.image %}
                        <img src="{{ user.profile.image.url }}" style="height:100%; width:100%; border-radius: 50%;">
                        {% else %}
                        <img src="{% static 'instagram/undefined_profile.jpg' %}" style="height:100%; width:100%; border-radius: 50%;">
                        {% endif %}
                    </a>
                </div>
                <div class="sec-aside-pf-name-box">
                    <div class="sec-aside-pf-name-nk-box">
                        <a href="{% url 'accounts:profile' %}" class="sec-aside-pf-name-nk">
                            {{ user.profile.nickname }}
                        </a>
                    </div>
                    <div class="sec-aside-pf-name-n-box">
                        {{ user.username }}
                    </div>
                </div>
            </div>
        </div>
        <div class="sas-b">
            <div class="sast-b">
                <div class="sastt-b">
                    <div class="sasttt">
                        스토리
                    </div>
                </div>
                <a href="#" class="sasta-b">
                    <div class="sastaa">
                        모두 보기
                    </div>
                </a>
            </div>
            <div class="sasc-m1">
                <div class="sasc-m2">
                    <div class="sasc-b">
                        <div class="sasc-ib">
                            <!-- 새 글 있으면 반복문 -->
                            <!-- 일단은 모든 유저 -->
                            {% for each_user in users %}
                                {% if each_user != user %}
                                {% if not each_user.is_superuser %}
                                <div style="height: 52px;">
                                    <!--원래는 버튼(밑)-->
                                    <div class="sasce-b">
                                        <div class="sascep-b" href="{% url 'accounts:detail' each_user.pk %}" role="button">
                                            {% if each_user.profile.image %}
                                            <img role="link" src="{{ each_user.profile.image.url }}" class="sascep">
                                            {% else %}
                                            <img role="link" src="{% static 'instagram/undefined_profile.jpg' %}" class="sascep">
                                            {% endif %}
                                        </div>
                                        <div class="sascec-b">
                                            <div class="sascecnk-b">
                                                <span>
                                                    {% if eachuser.profile.nickname %}
                                                        {{ each_user.profile.nickname }}
                                                    {% else %}
                                                        {{ each_user.username }}
                                                    {% endif %}
                                                </span>
                                            </div>
                                            <div class="sascect-b">
                                                <!--시간표시-->
                                                <!--나중에 수정해야함-->
                                                <span class="sascect">
                                                3시간 전
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}
                                {% endif %}
                            {% endfor %}
                            <!-- 반복문 끝 -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 추천이네 위랑 같아서 복붙 -->
        <div class="sar-b">
            <div class="sast-b">
                <div class="sastt-b">
                    <div class="sasttt">
                        회원님을 위한 추천
                    </div>
                </div>
                <a href="#" class="sasta-b">
                    <div class="sastaa">
                        모두 보기
                    </div>
                </a>
            </div>
            <div class="sarc-m1">
                <div class="sarc-m2">
                    <div class="sarc-b">
                        <div class="sarc-ib">
                            {% for each_user in users %}
                                {% if each_user not in user.followings.all %}
                                {% if not each_user.is_superuser %}
                                <div class="sarce-b">
                                    <!--원래는 버튼(밑)-->
                                    <div class="sascep-b" href="{% url 'accounts:detail' each_user.pk %}" role="button">
                                        {% if each_user.profile.image %}
                                        <img role="link" src="{{ each_user.profile.image.url }}" class="sascep">
                                        {% else %}
                                        <img role="link" src="{% static 'instagram/undefined_profile.jpg' %}" class="sascep">
                                        {% endif %}
                                    </div>
                                    <div class="sascec-b" style="margin-left: 12px;">
                                        <div class="sascecnk-b">
                                            <span>
                                                {% if each_user.profile.nickname %}
                                                    {{ each_user.profile.nickname }}
                                                {% else %}
                                                    {{ each_user.username }}
                                                {% endif %}
                                            </span>
                                        </div>
                                        <div class="sascect-b">
                                            <!--시간꺼 갖다 쓰기만 함-->
                                            <!--이건 어쩔수 없음 그냥 통일-->
                                            <span class="sascect" style="font-size: 12px;">
                                            Facebook 친구
                                            </span>
                                        </div>
                                    </div>
                                    <div class="sarcecf-b">
                                        <a href="{% url 'accounts:follow' each_user.pk %}" class="sarcecf">
                                            팔로우
                                        </a>
                                    </div>
                                </div>
                                {% endif %}
                                {% endif %}
                            {% endfor %}
                            <!-- 반복문 끝 -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="saf-b">
            <nav class="safn-b">
                <ul class="safnu-b">
                    <li class="safnul"><a href="#" class="safnul">INSTAGRAMU 정보</a></li>
                    <li class="safnul"><a href="#" class="safnul">후원</a></li>
                    <li class="safnul"><a href="#" class="safnul">회원목록</a></li>
                    <li class="safnul"><a href="#" class="safnul">어디로든 문</a></li>
                    <li class="safnul"><a href="#" class="safnul">???</a></li>
                </ul>
            </nav>
            <span class="saff">
                © 2019 INSTAGRAMU
            </span>
        </div>
    </div>
</div>

posts/templates/posts/_cards.html
{% load static %}
<div class="sec-article">
        <div class="sec-article-box">
            {% for post in posts %}
            <div class="cards-box-round">
                <header class="card-title">
                    <div class="card-title-photo">
                        <div class="card-title-canvas" role="button" href="{% url 'accounts:detail' post.user.pk %}">
                        </div>
                        <a href="#" style="width: 34px; height: 34px;">
                            {% if post.user.profile.image %}
                            <img src="{{ post.user.profile.image.url }}" style="height: 34px; width:34px;">
                            {% else %}
                            <img src="{% static 'instagram/undefined_profile.jpg' %}" style="height: 34px; width:34px;">
                            {% endif %}
                        </a>
                    </div>
                    
                    <div class="ctnk-b">
                        <a href="{% url 'accounts:detail' post.user.pk %}" class="ctnk">
                            {% if post.user.profile.nickname %}
                                {{ post.user.profile.nickname }}
                            {% else %}
                                {{ post.user.username }}
                            {% endif %}
                        </a>
                    </div>
                </header>
                <div class="cc-b">
                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            {% for image in post.image_set.all %}
                            <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                                <img src="{{ image.thumbnail_fill.url }}" class="d-block w-100" alt="{{ image }}">
                            </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>
                    <!--<img src="{{ post.image_set.first.file.url }}" width="100%" alt="picture">-->
                </div>
                <div class="cc2-b">
                    <section class="cc2n-b">
                        <span class="cc2nh-b">
                            <a href="{% url 'posts:like' post.pk %}" name="post-{{ post.pk }}">
                                <div class="cc2nh-ib">
                                    {% if user in post.like_users.all %}
                                        <span class="nav-icon cc2nhf"></span>
                                    {% else %}
                                        <span class="nav-icon cc2nh"></span>
                                    {% endif %}
                                </div>
                            </a>
                        </span>
                        <span class="cc2nc-b">
                            <a href="#" name="post-{{ post.pk }}">
                                <div class="cc2nh-ib">
                                    <span class="nav-icon cc2nc"></span>
                                </div>
                            </a>
                        </span>
                        <span class="cc2nu-b">
                            <a href="#" name="post-{{ post.pk }}">
                                <div class="cc2nh-ib">
                                    <span class="nav-icon cc2nu"></span>
                                </div>
                            </a>
                        </span>
                        <span class="cc2nb-b">
                            <a href="#" name="post-{{ post.pk }}">
                                <div class="cc2nh-ib">
                                    <span class="nav-icon cc2nb"></span>
                                </div>
                            </a>
                        </span>
                    </section>
                    <section class="cc2l-b">
                        <div class="cc2l-ib">
                            <a href="">
                                <!--Modal 연결-->
                                <span class="cc2l">
                                    좋아요 
                                    {{ post.like_users.all.count }}개
                                </span>
                            </a>
                        </div>
                    </section>
                    <div class="cc2c-b">
                        <ul class="cc2c-u">
                            <!--컨텐츠 추가해야함 -->
                            <li class="content"></li>
                            <li class="seeall"></li>
                            <li class="cc2c-comments-box">
                                {% for comment in post.comment_set.all %}
                                    <div class="cc2cc-each-box">
                                        <div class="cc2cce-comment-box">
                                            <a href="{% url 'accounts:detail' comment.user.pk %}" class="cc2cce-nkname">
                                                <!--댓쓴이에게 이동-->
                                                {% if comment.user.profile.nickname %}
                                                    {{ comment.user.profile.nickname }}
                                                {% else %}
                                                    {{ comment.user.username }}
                                                {% endif %}
                                            </a>
                                            <span style="font-size: 14px;">
                                                {{ comment.content }}
                                            </span>
                                        </div>
                                        <span class="cc2cce-heart">
                                            <!--추가해야하나.. 댓글 좋아요는 아직인데..-->
                                        </span>
                                    </div>
                                {% endfor %}
                            </li>
                        </ul>
                    </div>
                    <div class="cc2t-b">
                        
                    </div>
                    <section class="cc2wc-b">
                        
                    </section>
                    
                    <div class="comments">
                    </div>
                    <section class="comment-box d-flex align-items-center">
                        <div class="inner-box">
                            <form action="{% url 'posts:comment_new' post.pk %}" method="POST" class="comment-form d-flex align-items-center">
                                {% csrf_token %}
                                <textarea type="text" name="content" class="write-box" placeholder="댓글 달기..."></textarea>
                                <button type="submit" class="write-button">게시</button>
                            </form>
                        </div>
                    </section>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container article">
    {{ post.title }}
    {{ post.content }}
    <a href="{% url 'posts:edit' post.pk %}">수정하기</a>
    <a href="{% url 'posts:delete' post.pk %}">삭제하기</a>
    <div id="carouselExampleControls" class="carousel slide" style="" data-ride="carousel">
  <div class="carousel-inner">
    {% for image in post.image_set.all %}
    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
      <img src="{{ image.thumbnail_fill.url }}" class="" alt="{{ image }}" height="600px">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>
{% endblock %}

posts/templates/posts/form.html
{% extends 'base.html' %}

{% block body %}
<div class="post-form-box">
    <span class="post-form-title">글 작성하기</span><br>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if image_form %}
            {{ image_form }}
        {% endif %}
        {{ post_form }}
        <input type="submit" class="post-button">
    </form>
</div>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %} 
{% load static %}
{% block body %}
<section class="section-box">
    <div class="d-none d-lg-flex" style="margin-top: -2px;">
        {% include 'posts/_cards.html' %}
        {% include 'posts/_aside.html' %}
    </div>
    <div class="d-block d-lg-none underconstruct">
        <span>지원하지 않는 크기의 뷰입니다</span>
    </div>
</section>
<br><br><br><br><br><br>
{% endblock %}